language: java
jdk:
  - openjdk8
before_install:
  - sudo apt-get -y install jq
  - java -Xmx32m -version
before_script:
  - ls -lah
addons:
  apt:
    packages:
      - openjdk-8-jdk

env:
  global:
    - JAVA_HOME="/usr/lib/jvm/java-8-openjdk-amd64"
    - PATH="$JAVA_HOME/bin:$PATH"
    - USER_LOGIN="test-user"
    - USER_PASSWORD="Fqvq1s0S"
    - MOBILE_PLATFORM_NAME="iOS"
    - MOBILE_PLATFORM_VERSION="13.0"
    - MOBILE_DEVICE="iPhone XS Simulator"
    - WITH_DRIVER_PARAMS="-Dwebdriver.remote.url=$REMOTE_URL"
    - WITH_PLATFORM_PARAMS="-Dmobile.platform.name=$MOBILE_PLATFORM_NAME -Dmobile.platform.version=$MOBILE_PLATFORM_VERSION"
    - WITH_TESTS_PARAMS="-Dreport.portal.user=$USER_LOGIN -Dreport.portal.password=$USER_PASSWORD -Drp.uuid=$REPORTPORTAL_UUID"


stages:
  - prepare
  - compile
  - test

jobs:
  include:
    - stage: prepare
      name: Welcome to jdi light mobile demo
      script:
        - echo ------------------- WELCOME TO JDI LIGHT MOBILE DEMO ----------------------
        - mvn --version

    - stage: compile
      name: Compile jdi light mobile demo code
      script:
        - mvn install -DskipTests

    - stage: test
      name: Run tests
      script:
        - mvn -ntp install -DskipTests
        - mvn verify -Pdebug $WITH_TESTS_PARAMS $WITH_DRIVER_PARAMS $WITH_PLATFORM_PARAMS "-Dmobile.device.name=$MOBILE_DEVICE"

after_failure:
  - echo "Build was failed"
after_success:
  - echo "Build was successful"
after_script:
  - du -d 1 -h ./
  - ls -la
# extra time during long builds
install:
  - travis_wait